### ISSUE TITLE
No module named 'revtorch

### ISSUE THREAD

**Issue by jiaowoxielaoban** [Healingl/APRNet#1]
hello sir, why “No module named 'revtorch'” ，and I can't import revtorch in pycahrm console

**Comment by Healingl** [comment]
I have packaged the revtorch library in our project, you can use it directly: from lib.model.revtorch import revtorch as rv. Or, you can install it follow the original project: https://github.com/RobinBruegger/RevTorch

**Comment by jiaowoxielaoban** [comment]
> I have packaged the revtorch library in our project, you can use it directly: from lib.model.revtorch import revtorch as rv. Or, you can install it follow the original project: https://github.com/RobinBruegger/RevTorch

Thank you, I have solve this problem
