### ISSUE TITLE
HD95 compute error in APRNet

### ISSUE THREAD

**Issue by jiaowoxielaoban** [Healingl/APRNet#2]
Hi sir, when I train the model (APRNet) on the Iseg2017,   the value of hd95 will be calculated incorrectly, and after many epochs of training, its value will always approach 1.0, which is too different from the results given in the paper. So I would like to ask the author how to set the correct parameters to calculate hd95, thank you very much!

**Comment by Healingl** [comment]
> Hi sir, when I train the model (APRNet) on the Iseg2017, the value of hd95 will be calculated incorrectly, and after many epochs of training, its value will always approach 1.0, which is too different from the results given in the paper. So I would like to ask the author how to set the correct parameters to calculate hd95, thank you very much!

In the training procedures, the DSC values and ASD values can evaluate the performance of training networks easily. But if you want to evaluate the overall performance correctly, you can save segmentation results and calculate the metrics, for example,  you can refer to this project: https://github.com/hjkuijf/MRBrainS18

**Comment by jiaowoxielaoban** [comment]
> 

Thanks for your reply!!!
